server:
  port: 8080

spring:
  application:
    name: twitter-backend
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/twitter_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:rootpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: none
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
  cloud:
    azure:
      storage:
        blob:
          endpoint: https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
          account-key: ${AZURE_STORAGE_ACCOUNT_ACCESS_KEY}
          container-name: tweet-media  # Make sure this container exists in Azure!
  flyway:
    enabled: false
  web:
    error:
      include-stacktrace: never

jwt:
  # Secret must be 32+ chars. Run `openssl rand -base64 32` to generate one.
  secret: 9a8b7c6d5e4f3g2h1i0j9k8l7m6n5o4p3q2r1s0t9u8v7w6x5y4z3a2b1c0d
  access-expiration: 1800000   # 30 minutes (Short lived)
  refresh-expiration: 2592000000 # 30 Days (Long lived)

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}