name: Trigger auto deployment for ca-chntwt-api-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-chntwt-api-dev-AutoDeployTrigger-fad1c99f-5756-46a5-8087-92ad712ed66e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CACHNTWTAPIDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CACHNTWTAPIDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CACHNTWTAPIDEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/twitter-backend/dockerfile
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: crchntwtdevsea001.azurecr.io
          registryUsername: ${{ secrets.CACHNTWTAPIDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CACHNTWTAPIDEV_REGISTRY_PASSWORD }}
          containerAppName: ca-chntwt-api-dev
          resourceGroup: rg-chntwt-dev-sea
          imageToBuild: crchntwtdevsea001.azurecr.io/ca-chntwt-api-dev:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


